import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Footer } from "@/components/Footer";
import { cookieToInitialState } from "wagmi";

import { config } from "@/configwallet";
import Provider from "@/components/wallet/Provider";

export const metadata: Metadata = {
  title: "Encyclochain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body>
        <Provider initialState={initialState}>{children}</Provider>
        <Footer></Footer>
      </body>
    </html>
  );
}
